### ISSUE TITLE
Add Installation Description

### ISSUE THREAD

**Issue by seunzone** [asifsha/react-jet#7]
A nice job was done on the project, going through the code and screenshots on the readme it looks good.
However, there should be descriptions on how to install and start the application in the readme, also if one needs to connect to an API to get all functionalities fully running, it should also be clearly stated in the readme as well.

**Comment by asifsha** [comment]
Thanks,
Installation instructions and API details added to readme.

**Comment by seunzone** [comment]
Awesome 🔥
